import { images } from "./images";

export const data = {
  menuItems: ["Experience", "Skills", "Projects", "Education"],
  experience: [
    {
      img: images.ibsLogo,
      company: "IBS Software",
      role: "Team Lead",
      period: "November 2021 to Present",
      location: "Cochin, Kerala, India",
      skills:
        "Typescript, React Js, React Hooks, Redux toolkit, HTML5, CSS3, Styled components, React bootstrap, Electron JS, Node JS, Saas",
      sliderImages: [
        images.ts,
        images.react,
        images.react_hooks,
        images.redux,
        images.html5,
        images.css,
        images.styled,
        images.bootstrap,
        images.electron,
        images.node,
        images.sass,
      ],
      rolesAndResponsibilities: [
        "Leading a team of 10 members and managing resource allocation, schedule and documentation.",
        "Worked closely with architecture team for the design, technology selection, research and POCs for the project",
        "Collaboratively worked with different teams for requirement gathering, development, API integrations and testing to ensure the customer satisfaction",
        "Implemented multiple complex modules, created desktop application using Electron JS, unit tested and delivered",
        "Monitored the development of junior resources, mentored them and guided them with proper code review and coding best practices",
      ],
    },
    {
      img: images.bnFull,
      company: "BuildNext",
      role: "Software Developer",
      period: "October 2015 to November 2021",
      location: "Cochin, Kerala, India",
      skills:
        "JavaScript, jQuery, React Native, Redux, HTML5, CSS3, Vue Js, Bootstrap, Material UI, Ajax, JSON",
      sliderImages: [
        images.js,
        images.jq,
        images.react_native,
        images.redux,
        images.html5,
        images.css,
        images.vue,
        images.bootstrap,
        images.material,
      ],
      rolesAndResponsibilities: [
        "Implemented different modules which are maintainable and scalable by following best coding practices",
        "Wrote clean, clear and well-tested code with proper documentation for various projects",
        "Owned the architecture design, development and deployment of the hybrid mobile application created with React Native",
        "Improved user experience by the innovative forward-thinking and critical problem solving skills",
        "Managed to mentor junior developers and support them to grow with industrial standards",
      ],
    },
    {
      img: images.qburst,
      company: "QBurst",
      role: "Frontend Developer",
      period: "September 2012 to September 2015",
      location: "Trivandrum, Kerala, India",
      skills:
        "JavaScript, jQuery, AngularJS, React JS, HTML5, CSS3, Bootstrap, JSON",
      sliderImages: [
        images.js,
        images.jq,
        images.angular,
        images.react,
        images.html5,
        images.css,
        images.bootstrap,
      ],
      rolesAndResponsibilities: [
        "Wrote clean, clear and well-tested code with proper documentation for various projects",
        "Collaboratively worked with different teams such as graphical designers, backend developers and testers to provide quality product for customers",
        "Developed responsive web applications with the help of media queries, plugins & widgets using jQuery and integrated REST APIs for multiple projects",
      ],
    },
    {
      img: images.freelance,
      company: "Freelance",
      role: "Frontend Architect and Developer",
      period: "April 2017 to September 2022",
      location: "Remote",
      skills:
        "JavaScript, Typescript, React JS, React Hooks, React Native, Redux, Next JS, Node JS, HTML5, CSS3, React Bootstrap, Styled Components, JSON",
      sliderImages: [
        images.js,
        images.ts,
        images.react,
        images.react_native,
        images.react_hooks,
        images.redux,
        images.html5,
        images.css,
        images.node,
        images.bootstrap,
        images.styled,
      ],
      rolesAndResponsibilities: [
        "Owned the architecture design, development and deployment of the hybrid mobile and web applications created with React JS and React Native",
        "Wrote clean, clear and well-tested code with proper documentation for various projects",
        "Collaboratively worked with different teams such as graphical designers, backend developers and testers to provide quality product for customers",
        "Developed responsive web applications with the help of media queries",
        "Implemented multiple complex modules",
      ],
    },
  ],
  skills: [
    {
      img: images.js,
      title: "JavaScript",
      experience: "10 years",
      rating: "90%",
    },
    {
      img: images.ts,
      title: "TypeScript",
      experience: "3 years",
      rating: "75%",
    },
    {
      img: images.react,
      title: "React JS",
      experience: "5 years",
      rating: "85%",
    },
    {
      img: images.react_native,
      title: "React Native",
      experience: "4 years",
      rating: "75%",
    },
    {
      img: images.react_hooks,
      title: "React Hooks",
      experience: "3 years",
      rating: "80%",
    },
    {
      img: images.redux,
      title: "Redux",
      experience: "5 years",
      rating: "85%",
    },
    {
      img: images.redux,
      title: "Redux Toolkit",
      experience: "1.5 years",
      rating: "80%",
    },
    {
      img: images.jq,
      title: "jQuery",
      experience: "6 years",
      rating: "85%",
    },
    {
      img: images.vue,
      title: "Vue JS",
      experience: "1.5 years",
      rating: "60%",
    },
    {
      img: images.node,
      title: "Node JS",
      experience: "1.5 years",
      rating: "60%",
    },
    {
      img: images.angular,
      title: "Angular JS",
      experience: "1.5 years",
      rating: "50%",
    },
    {
      img: images.electron,
      title: "Electron JS",
      experience: "1.5 years",
      rating: "70%",
    },
    {
      img: images.html5,
      title: "HTML5",
      experience: "10 years",
      rating: "80%",
    },
    {
      img: images.css,
      title: "CSS3",
      experience: "10 years",
      rating: "75%",
    },
    {
      img: images.sass,
      title: "Sass",
      experience: "3.5 years",
      rating: "70%",
    },
    {
      img: images.bootstrap,
      title: "Bootstrap",
      experience: "7 years",
      rating: "80%",
    },
    {
      img: images.styled,
      title: "Styled Components",
      experience: "3 years",
      rating: "75%",
    },
    {
      img: images.material,
      title: "Material UI",
      experience: "2.5 years",
      rating: "65%",
    },
  ],
  projects: [
    {
      img: images.ana,
      title: "APaSS-BOOK",
      company: "IBS Software",
      type: "Web Applications",
      sliderImages: [
        images.js,
        images.ts,
        images.react,
        images.react_hooks,
        images.redux,
        images.html5,
        images.css,
        images.sass,
        images.node,
        images.electron,
        images.bootstrap,
        images.styled,
      ],
      description:
        "Airline reservation system for ANA booking agents. Currently they are using the Marvel desktop application. This project converts the current Marvel Desktop app into APaSS-BOOK",
    },
    {
      img: images.bnFull,
      title: "BuildNext Web",
      company: "BuildNext",
      type: "Web application",
      sliderImages: [
        images.js,
        images.jq,
        images.vue,
        images.html5,
        images.css,
        images.bootstrap,
        images.material,
      ],
      description:
        "BuildNext is a tech-enabled home builder with the sole purpose of improving customer experience in the building construction industry.",
    },
    {
      img: images.bnMobile,
      title: "BuildNext App",
      company: "BuildNext",
      type: "Mobile Application",
      sliderImages: [images.ts, images.react_native, images.redux, images.css],
      description:
        "BuildNext is a tech-enabled home builder with the sole purpose of improving customer experience in the building construction industry. This app is a must-have companion for BuildNext customers, partner professionals as well as anyone interested in building their dream home. It is an integral part of the BuildNext customer journey right from ideation of their dream project through design, product selection, planning and daily work progress tracking all the way to project handover and support.",
    },
    {
      img: images.bnFull,
      title: "BuildNext Sales-partner Dashboard",
      company: "BuildNext",
      type: "Web application",
      sliderImages: [
        images.js,
        images.jq,
        images.react,
        images.html5,
        images.css,
        images.bootstrap,
        images.material,
      ],
      description:
        "BuildNext is a tech-enabled home builder with the sole purpose of improving customer experience in the building construction industry. Salespartner module is a dashboard for BuildNext partners to check their details. Main fetures of the dashbord includes payment info, project info, order info, pending and settled payments etc.",
    },
    {
      img: images.propicks,
      title: "PropPicks",
      company: "QBurst",
      type: "Web Application",
      sliderImages: [
        images.js,
        images.ts,
        images.angular,
        images.html5,
        images.css,
        images.sass,
        images.bootstrap,
      ],
      description:
        "The objective of the project is to develop a fantasy sports platform for popular sports like football and basketball. The registered users can search for other users, select the contest type, build teams and play daily/weekly games hosted on the platform.",
    },
    {
      img: images.nightHq,
      title: "NightHub",
      company: "QBurst",
      type: "Web Application",
      sliderImages: [
        images.js,
        images.jq,
        images.html5,
        images.css,
        images.sass,
        images.bootstrap,
      ],
      description:
        "NightHQ is a Web and mobile application that is going to disrupt the Nightlife industry using proven eCommerce models combined with a highly integrated viral adoption system.",
    },
    {
      img: images.everfi,
      title: "Everfi",
      company: "QBurst",
      type: "Web Application",
      sliderImages: [
        images.js,
        images.jq,
        images.html5,
        images.css,
        images.bootstrap,
      ],
      description:
        "Everfi was a web curriculum new-media learning platform that uses cutting-edge instructional design, rich media, and simulations to educate teens and empower them with the skill set to leverage technology safely and effectively done in Flash technology.",
    },
  ],
  education: [
    {
      img: images.faith,
      title: "Java Trainee",
      institute: "Faith Infotech",
      level: "Post B-Tech",
      period: "June 2012 - September 2012",
      marksSecured: null,
    },
    {
      img: images.cec,
      title: "B-TECH",
      institute: "College of Engineering, Chengannur",
      level: "Graduate",
      period: "September 2008 - May 2012",
      marksSecured: "60%",
    },
    {
      img: images.hss,
      title: "Plus Two",
      institute: "St Mary's HSS Kuravilangad",
      level: "Higher Secondary",
      period: "June 2005 - March 2007",
      marksSecured: "83%",
    },
    {
      img: images.hss,
      title: "SSLC",
      institute: "St Mary's HSS Kuravilangad",
      level: "Secondary",
      period: "June 2004 - March 2005",
      marksSecured: "90%",
    },
  ],
};
